# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0003_auto_20161124_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('MERQ', 'Mergers and Acquisitions'), ('MRKT', 'Markets'), ('RKMN', 'Risk Management'), ('SCRT', 'Securities'), ('FIMO', 'Financial Modelling'), ('OPER', 'Operations'), ('IFTC', 'Information Technology')], default='MERQ', max_length=4, null=True),
        ),
    ]
