# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0010_enrollment_progerss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='progerss',
            new_name='progress',
        ),
    ]
